### ISSUE TITLE
Add options for text output

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Content-Restriction#17] opened 2015-07-10 13:00 UTC
We're often asked how to change the messages displayed when users don't have access to content. Would be nice to have options for those.

**Comment by pippinsplugins** [comment] 2015-07-23 20:57
It would be nice to have a setting for this.

**Comment by cklosowski** [comment] 2015-09-14 22:44
@mindctrl @pippinsplugins curious what you guys think. of the commits made here for `issue/17` branch

**Comment by pippinsplugins** [comment] 2015-09-15 21:39
Looks good, though the first thing people are going to ask for is product-specific messages. Thoughts on adding an option for that in the CR metabox?

**Comment by cklosowski** [comment] 2015-09-16 22:10
I think it's feasible, but should be in a separate issue.

**Comment by cklosowski** [comment] 2015-09-16 22:21
The reason I say new issue is:
a) First let's root out any weird issues we have with the current system in the PR
b) Let's see IF it's actually requested a ton, we know users have been wanting this feature, and it could appease them for now, while we work on adding the per-product ones in a later update, after this has had some time to bake and prove itself in the wild.

**Comment by pippinsplugins** [comment] 2015-09-16 22:25
:+1:

**Comment by mindctrl** [comment] 2015-09-16 22:35
@cklosowski I think we need to run this through wpautop. Not getting line breaks in my custom messages.

**Comment by cklosowski** [comment] 2015-09-17 18:46
@mindctrl will test it out.

**Comment by cklosowski** [comment] 2015-09-17 18:56
Confirmed that we need `wpautop( $message )` to be sure it returns correctly with the white spacing in tact.

**Comment by mindctrl** [comment] 2015-09-17 19:26
@cklosowski looks good now.

**Comment by cklosowski** [comment] 2015-09-17 19:48
cool merging and closing

**Closed** 2015-09-17 19:49 UTC
Labels: enhancement, Has PR
